# Temporal Awareness Pre-Check Workflow
# Finance Guru™ v2.0
# Powered by BMAD-CORE™

name: "Temporal Awareness Pre-Check"
description: "Ensures current date is known and enforced before any web search or market research activity"
version: "1.0.0"
category: "system-validation"
module: "fin-guru"
author: "Ossie"
created: "2025-10-12"

# Workflow Purpose
purpose: |
  This workflow is MANDATORY before any web search, market research, or data gathering activity.
  It establishes temporal context to ensure all searches include current date qualifiers,
  preventing the retrieval of outdated information that could lead to poor investment decisions.

# Execution Context
execution:
  trigger: "before-any-web-search"
  priority: "critical"
  blocking: true
  retry_on_fail: true
  max_retries: 3

# Workflow Steps
steps:
  - id: "step-1-get-full-datetime"
    name: "Retrieve Full Current DateTime"
    type: "bash"
    description: "Get full current date and time (e.g., 'Sun Oct 12 23:53:51 CDT 2025')"
    command: "date"
    store_as: "current_datetime"
    mandatory: true
    validation:
      - check: "current_datetime is not empty"
        error: "CRITICAL: Failed to retrieve current datetime. Cannot proceed with web searches."
    on_success: "step-2-get-structured-date"
    on_fail: "error-handler"

  - id: "step-2-get-structured-date"
    name: "Retrieve Structured Date"
    type: "bash"
    description: "Get structured date in YYYY-MM-DD format for documentation"
    command: "date +%Y-%m-%d"
    store_as: "current_date"
    mandatory: true
    validation:
      - check: "current_date is not empty"
        error: "CRITICAL: Failed to retrieve structured date. Cannot proceed with web searches."
    on_success: "step-3-validate-temporal-context"
    on_fail: "error-handler"

  - id: "step-3-validate-temporal-context"
    name: "Validate Temporal Context"
    type: "validation"
    description: "Ensure all temporal variables are properly set"
    checks:
      - condition: "{current_datetime} is not empty"
        message: "Full datetime validation"
      - condition: "{current_date} matches pattern YYYY-MM-DD"
        message: "Structured date format validation"
    mandatory: true
    on_success: "step-4-display-temporal-context"
    on_fail: "error-handler"

  - id: "step-4-display-temporal-context"
    name: "Display Temporal Context"
    type: "output"
    description: "Confirm temporal awareness is established"
    message: |
      ✅ TEMPORAL AWARENESS CONFIRMED

      Current DateTime: {current_datetime}
      Structured Date: {current_date}

      📋 Search Enhancement Rules Active:
      • All web searches MUST include temporal qualifiers from {current_datetime}
      • Use month and year (e.g., "October 2025") in queries for current data
      • Use "latest" or "current" for most recent information
      • Flag any sources older than data freshness requirements

      ⚠️ Data Freshness Requirements:
      • Market data: Same-day only
      • Economic data: Within 30 days
      • Regulatory data: Within 90 days
      • Company data: Current quarter
    on_success: "workflow-complete"

  - id: "error-handler"
    name: "Temporal Check Error Handler"
    type: "error"
    description: "Handle temporal awareness failures"
    actions:
      - log: "CRITICAL ERROR: Temporal awareness check failed"
      - notify: "Cannot proceed with web searches - temporal context not established"
      - stop: true
    message: |
      🚨 CRITICAL ERROR: Temporal Awareness Check Failed

      The system could not establish current date context, which is MANDATORY
      for Finance Guru™ operations. All market research and web searches are
      BLOCKED until this issue is resolved.

      Possible causes:
      • System date/time not accessible
      • Date command unavailable
      • Invalid date format returned

      ACTION REQUIRED: Verify system date settings and retry.

  - id: "workflow-complete"
    name: "Workflow Complete"
    type: "success"
    description: "Temporal awareness successfully established"
    message: "Temporal context established. Proceeding with temporally-aware operations."

# Output Variables
outputs:
  - name: "current_datetime"
    type: "string"
    format: "Full datetime (e.g., 'Sun Oct 12 23:53:51 CDT 2025')"
    description: "Complete current date and time with month, day, year, and timezone"
    usage: "Use for temporal context in search queries (e.g., 'Tesla analysis October 2025')"

  - name: "current_date"
    type: "string"
    format: "YYYY-MM-DD"
    description: "Structured current date for documentation and timestamps"
    usage: "Include in all research documentation and source citations"

# Integration Points
integration:
  - agent: "market-researcher"
    trigger: "before-any-search"
    required: true

  - agent: "strategy-advisor"
    trigger: "before-market-analysis"
    required: true

  - agent: "finance-orchestrator"
    trigger: "session-start"
    required: true

  - agent: "quant-analyst"
    trigger: "before-data-collection"
    required: true

  - agent: "compliance-officer"
    trigger: "before-regulatory-research"
    required: true

# Usage Examples
examples:
  - scenario: "Market Research Initialization"
    description: "Run before any market intelligence gathering"
    invocation: "Execute temporal-check workflow before initiating research"
    expected_output: "Current date and year variables set and confirmed"

  - scenario: "Search Query Enhancement"
    description: "Use temporal context to enhance search queries"
    before: "Tesla stock analysis"
    after: "Tesla stock analysis {current_year} latest"

  - scenario: "Source Validation"
    description: "Validate source freshness against requirements"
    check: "Is source date within acceptable freshness threshold?"
    action: "Flag or reject sources exceeding age limits"

# Validation Rules
validation_rules:
  search_queries:
    - rule: "All search queries MUST include {current_year} OR 'latest' OR 'current'"
      enforcement: "blocking"
      message: "Search query missing temporal qualifiers"

  data_sources:
    - rule: "Market data must be same-day"
      enforcement: "warning"
      message: "Market data source is not current"

    - rule: "Economic data must be within 30 days"
      enforcement: "warning"
      message: "Economic data may be outdated"

    - rule: "Regulatory data must be within 90 days"
      enforcement: "warning"
      message: "Regulatory information may be outdated"

# Error Handling
error_handling:
  retry_strategy:
    max_attempts: 3
    backoff: "exponential"
    initial_delay: "1s"

  fallback:
    action: "block-all-searches"
    message: "Temporal awareness is mandatory. Operations blocked until resolved."

  logging:
    level: "critical"
    destination: "system-log"
    include_context: true

# Metadata
metadata:
  bmad_version: "6.0.0"
  finance_guru_version: "2.0.0"
  workflow_type: "system-validation"
  criticality: "mandatory"
  frequency: "every-session-start"
  performance_target: "<1s"
